CP = cp

normal:
	$(CP) stgnum.png stysnum0.png
	$(CP) stgnum.png stysnum1.png
	$(CP) stgnum.png stysnum2.png
	$(CP) stgnum.png stysnum3.png
	$(CP) stgnum.png stysnum4.png
	$(CP) stgnum.png stysnum5.png
	$(CP) stgnum.png stysnum6.png
	$(CP) stgnum.png stysnum7.png
	$(CP) stgnum.png stysnum8.png
	$(CP) stgnum.png stysnum9.png
	$(CP) stgnum.png stgnum0.png
	$(CP) stgnum.png stgnum1.png
	$(CP) stgnum.png stgnum2.png
	$(CP) stgnum.png stgnum3.png
	$(CP) stgnum.png stgnum4.png
	$(CP) stgnum.png stgnum5.png
	$(CP) stgnum.png stgnum6.png
	$(CP) stgnum.png stgnum7.png
	$(CP) stgnum.png stgnum8.png
	$(CP) stgnum.png stgnum9.png

clean:
	$(RM) stysnum0.png
	$(RM) stysnum1.png
	$(RM) stysnum2.png
	$(RM) stysnum3.png
	$(RM) stysnum4.png
	$(RM) stysnum5.png
	$(RM) stysnum6.png
	$(RM) stysnum7.png
	$(RM) stysnum8.png
	$(RM) stysnum9.png
	$(RM) stgnum0.png
	$(RM) stgnum1.png
	$(RM) stgnum2.png
	$(RM) stgnum3.png
	$(RM) stgnum4.png
	$(RM) stgnum5.png
	$(RM) stgnum6.png
	$(RM) stgnum7.png
	$(RM) stgnum8.png
	$(RM) stgnum9.png
