CP = cp

normal:
	$(CP) sw_skull/sw_skull0.png sw1skull.png
	$(CP) sw_skull/sw_skull1.png rw48_4.png
	$(CP) sw_skull/sw_skull2.png rw48_2.png

clean:
	$(RM) rw48_4.png
	$(RM) rw48_2.png
	$(RM) sw1skull.png
