CP = cp

normal: soula0.png soulb0.png
	$(CP) soula0.png bkeya0.png
	$(CP) soulb0.png bkeyb0.png
	$(CP) soulc0.png bkeyc0.png
	$(CP) sould0.png bkeyd0.png
	$(CP) soula0.png rkeya0.png
	$(CP) soulb0.png rkeyb0.png
	$(CP) soulc0.png rkeyc0.png
	$(CP) sould0.png rkeyd0.png
	$(CP) soula0.png ykeya0.png
	$(CP) soulb0.png ykeyb0.png
	$(CP) soulc0.png ykeyc0.png
	$(CP) sould0.png ykeyd0.png
	$(CP) soula0.png bskua0.png
	$(CP) soulb0.png bskub0.png
	$(CP) soulc0.png bskuc0.png
	$(CP) sould0.png bskud0.png
	$(CP) soula0.png rskua0.png
	$(CP) soulb0.png rskub0.png
	$(CP) soulc0.png rskuc0.png
	$(CP) sould0.png rskud0.png
	$(CP) soula0.png yskua0.png
	$(CP) soulb0.png yskub0.png
	$(CP) soulc0.png yskuc0.png
	$(CP) sould0.png yskud0.png

goldskull:
	$(CP) golda0.png bkeya0.png
	$(CP) goldb0.png bkeyb0.png
	$(CP) golda0.png rkeya0.png
	$(CP) goldb0.png rkeyb0.png
	$(CP) golda0.png ykeya0.png
	$(CP) goldb0.png ykeyb0.png
	$(CP) golda0.png bskua0.png
	$(CP) goldb0.png bskub0.png
	$(CP) golda0.png rskua0.png
	$(CP) goldb0.png rskub0.png
	$(CP) golda0.png yskua0.png
	$(CP) goldb0.png yskub0.png

clean:
	$(RM) bkeya0.png
	$(RM) bkeyb0.png
	$(RM) bkeyc0.png
	$(RM) bkeyd0.png
	$(RM) rkeya0.png
	$(RM) rkeyb0.png
	$(RM) rkeyc0.png
	$(RM) rkeyd0.png
	$(RM) ykeya0.png
	$(RM) ykeyb0.png
	$(RM) ykeyc0.png
	$(RM) ykeyd0.png
	$(RM) bskua0.png
	$(RM) bskub0.png
	$(RM) bskuc0.png
	$(RM) bskud0.png
	$(RM) rskua0.png
	$(RM) rskub0.png
	$(RM) rskuc0.png
	$(RM) rskud0.png
	$(RM) yskua0.png
	$(RM) yskub0.png
	$(RM) yskuc0.png
	$(RM) yskud0.png
